### ISSUE TITLE
Last physical device selected even if it is not suitable

### ISSUE THREAD

**Issue by cpope9141** [Naitsirc98/Vulkan-Tutorial-Java#10]
This is related to the list of available extensions not being populated in chapter 6. I've noticed that if none of the physical devices are suitable, local variable 'device' in pickPhysicalDevice() will be the last of the non-suitable devices (i.e. not null). So, the run time exception is not thrown and the program continues having selected the last non-suitable device. Adding an else clause to the logic in the for loop that resets 'device' to null has worked for me.

private void pickPhysicalDevice() {

            try(MemoryStack stack = stackPush()) {

                IntBuffer deviceCount = stack.ints(0);

                vkEnumeratePhysicalDevices(instance, deviceCount, null);

                if(deviceCount.get(0) == 0) {
                    throw new RuntimeException("Failed to find GPUs with Vulkan support");
                }

                PointerBuffer ppPhysicalDevices = stack.mallocPointer(deviceCount.get(0));

                vkEnumeratePhysicalDevices(instance, deviceCount, ppPhysicalDevices);

                VkPhysicalDevice device = null;

                for(int i = 0;i < ppPhysicalDevices.capacity();i++) {

                    device = new VkPhysicalDevice(ppPhysicalDevices.get(i), instance);

                    if(isDeviceSuitable(device)) {
                        break;
                    }
                }

                if(device == null) {
                    throw new RuntimeException("Failed to find a suitable GPU");
                }

                physicalDevice = device;
            }
        }

**Comment by cpope9141** [comment]
If you are open to contributors, I am willing to submit changes for these small issues.

**Comment by Naitsirc98** [comment]
Hi,

True, it will never throw the RuntimeException. I think this could be a good way of fixing it:

        private void pickPhysicalDevice() {

            try(MemoryStack stack = stackPush()) {

                IntBuffer deviceCount = stack.ints(0);

                vkEnumeratePhysicalDevices(instance, deviceCount, null);

                if(deviceCount.get(0) == 0) {
                    throw new RuntimeException("Failed to find GPUs with Vulkan support");
                }

                PointerBuffer ppPhysicalDevices = stack.mallocPointer(deviceCount.get(0));

                vkEnumeratePhysicalDevices(instance, deviceCount, ppPhysicalDevices);

                for(int i = 0;i < ppPhysicalDevices.capacity();i++) {

                    VkPhysicalDevice device = new VkPhysicalDevice(ppPhysicalDevices.get(i), instance);

                    if(isDeviceSuitable(device)) {
                        physicalDevice = device;
                        return;
                    }
                }

                throw new RuntimeException("Failed to find a suitable GPU");
            }
        }

As you can see, it picks the first suitable device and returns inmediately, no need for additional if/else statements.

> If you are open to contributors, I am willing to submit changes for these small issues.

Sure, open a pull request with the fix and I will review and merge it as soon as possible. Don't forget to mention the issue reference in the commit message!

Thanks!

**Comment by cpope9141** [comment]
Your solution looks good to me. Thanks again for translating these tutorials to use LWJGL.
