### ISSUE TITLE
Better document methods to avoid and better understand potential memory leaks

### ISSUE THREAD

**Issue by ws909** [Naitsirc98/Vulkan-Tutorial-Java#16]
<strike>There's multiple memory leaks in this project.</strike>
`MemoryStack::stackGet()` is used multiple times to get the stack at its current location, content is then added to it, the stack's internal pointer is advanced, but this content is never removed from the stack.

One such example:
https://github.com/Naitsirc98/Vulkan-Tutorial-Java/blob/ff0567a6635322d0413196f2ceffe338eef52bdb/src/main/java/javavulkantutorial/Ch15HelloTriangle.java#L1065-L1076

**Comment by ws909** [comment]
One solution is this: 

```java
private PointerBuffer asPointerBuffer(Collection<String> collection, MemoryStack stack) {
    PointerBuffer buffer = stack.mallocPointer(collection.size());

    collection.stream()
            .map(stack::UTF8)
            .forEach(buffer::put);

    return buffer.rewind();
}

try (MemoryStack stack = MemoryStack.stackPush()) {
    ... = asPointerBuffer(..., stack);
}
```

**Comment by ws909** [comment]
On second thought, the callsites of `asPointerBuffer` already are wrapped in `try (MemoryStack stack = MemoryStack.stackPush())`. This does rewind the stack to its initial position.

But I managed to create this issue before taking note of that, so I believe you should document this and other such methods, slightly better. Also, passing the stack around potentially provides better performance than to repeatedly use `stackGet()`. The JIT might optimize that.

**Comment by Naitsirc98** [comment]
Hi @ws909,

Thank you for you comments. As you said in the last message, there are no memory leaks in `asPointerBuffer` because I call it inside a try-with-resources block.

I'm planning on doing a revision of this repository (to match the recent changes on the original tutorial) so I take your comments into account for that.
