### ISSUE TITLE
Ch17 - VkPipeline Validation Problem.

### ISSUE THREAD

**Issue by SWinxy** [Naitsirc98/Vulkan-Tutorial-Java#3]
> Validation layer problem: VkPipeline 0xc6ac6a000000000f[] expects that this Command Buffer's vertex binding Index 0 should be set via vkCmdBindVertexBuffers. This is because VkVertexInputBindingDescription struct at index 0 of pVertexBindingDescriptions has a binding value of 0. The Vulkan spec states: All vertex input bindings accessed via vertex input variables declared in the vertex shader entry point's interface must have valid buffers bound (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdDraw-None-02720)

Likely has to do with `pVertexBindingDescriptions` and `pVertexAttributeDescriptions`.

**Comment by SWinxy** [comment]
I couldn't have bothered to read the last lines of [the C++ tutorial](https://vulkan-tutorial.com/Vertex_buffers/Vertex_input_description) and naively assumed this was unintentional. I added a note of this in #4.

**Comment by Naitsirc98** [comment]
Yes, that error is intentional, as it is explained in the corresponding [chapter ](https://vulkan-tutorial.com/Vertex_buffers/Vertex_input_description) of the original tutorial: 

> _If you run the program now with validation layers enabled, you'll see that it complains that there is no vertex buffer bound to the binding. The next step is to create a vertex buffer and move the vertex data to it so the GPU is able to access it._

I'm closing this issue, then. Sorry for the late respond, I have been busy these last days. Btw, thank you for opening this issue, it will help other devs for sure.

**Comment by SWinxy** [comment]
If you could merge #4 I would appreciate that ^.^

**Comment by SWinxy** [comment]
Also, are the errors from the next chapters meant to be there?

What I get when running the Ch20 code:
>Validation layer: Shader uses descriptor slot 0.0 (expected `VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT`) but not declared in pipeline layout

>Validation layer: vkCmdDrawIndexed(): VkPipeline 0x40fd720000000017[] defined with VkPipelineLayout 0x3047930000000016[] is not compatible for maximum set statically used 0 with bound descriptor sets, last bound with VkPipelineLayout 0x0[] The Vulkan spec states: For each set n that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-None-02697)

>Validation layer: VkPipeline 0x40fd720000000017[] uses set #0 but that set is not bound.

>Validation layer: VkFence 0x30f5a50000000020[] is in use. The Vulkan spec states: Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkResetFences-pFences-01123)

**Comment by SWinxy** [comment]
I feel so f*cking stupid right now. Problem was that I accidentally skipped a few chapters, then realized and rolledback what I *thought* was everything, except for the vert shader, and *that* was what was giving me errors.

Should the repo mention when the shader is changed?
