### ISSUE TITLE
Ch02 how to test validation layers?

### ISSUE THREAD

**Issue by Yairama** [Naitsirc98/Vulkan-Tutorial-Java#7]
Hello, i want to test if validation layers are correctly implemented, in the original tutorial you can test it removing `DestroyDebugUtilsMessengerEXT` but when i remove this in the java example nothing happens.
any idea to test the validation layers?

**Comment by toongeorges** [comment]
I ran the code in Ch02ValidationLayers.java and the validation layers seemed to work there.  The messages are logged to System.err

Could you give more details about the code you are running?

**Comment by Naitsirc98** [comment]
For those who may be wondering why I output the debug messages to System.err instead of System.out, is simply because in the original tutorial it is logged to `std::cerr`:

https://github.com/Overv/VulkanTutorial/blob/3987b9d821ef2044df1c1508ffb570995447c609/code/02_validation_layers.cpp#L183-L188
