### ISSUE TITLE
Bug in Ch03PhysicalDeviceSelection.java code

### ISSUE THREAD

**Issue by toongeorges** [Naitsirc98/Vulkan-Tutorial-Java#8]
The following code contains a bug:

                indices.graphicsFamily = queueFamilies.stream()
                        .map(VkQueueFamilyProperties::queueFlags)
                        .filter(queueFlags -> (queueFlags & VK_QUEUE_GRAPHICS_BIT) != 0)
                        .findAny().orElse(null);

This code sets indices.graphicsFamily to the value of the queueFlag of a graphics queue family.  Instead indices.graphicsFamily has to be set to the index of the graphics queue family within queueFamilies.

Corrected code would be:

                for (int i = 0; i < queueFamilies.limit(); i++) {
                    int queueFlags = queueFamilies.get(i).queueFlags();
                    if ((queueFlags & VK_QUEUE_GRAPHICS_BIT) != 0) {
                        indices.graphicsFamily = i;
                        break;
                    }
                }

**Comment by Naitsirc98** [comment]
Hi @toongeorges! 

You are right! Thank you for pointing that out. I've already change it as it is in Ch04.
